INSERT INTO CUSTOMER (ID, NAME) VALUES (1, 'JONATHAN');
INSERT INTO CUSTOMER (ID, NAME) VALUES (2, 'GEORGE');
INSERT INTO CUSTOMER (ID, NAME) VALUES (3, 'JOSEPH');

INSERT INTO CATEGORY (ID, NAME) VALUES (1, 'TOYS');
INSERT INTO CATEGORY (ID, NAME) VALUES (2, 'CLOTHES');

INSERT INTO ITEM (ID, NAME, CATEGORY_ID, PRICE) VALUES (1, 'PUPPY', 1, 3.00);
INSERT INTO ITEM (ID, NAME, CATEGORY_ID, PRICE) VALUES (2, 'PLANE', 1, 4.00);
INSERT INTO ITEM (ID, NAME, CATEGORY_ID, PRICE) VALUES (3, 'CLACKERS', 1, 2.00);
INSERT INTO ITEM (ID, NAME, CATEGORY_ID, PRICE) VALUES (4, 'BOWTIE', 2, 5.00);
INSERT INTO ITEM (ID, NAME, CATEGORY_ID, PRICE) VALUES (5, 'UNIFORM', 2, 6.00);
INSERT INTO ITEM (ID, NAME, CATEGORY_ID, PRICE) VALUES (6, 'SCARF', 2, 7.00);

